"""add_fecha_seguimiento_cobro_to_appointment

Revision ID: 027b9cb4171d
Revises: fbec71fd9b9f
Create Date: 2026-07-20 22:30:28.109182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027b9cb4171d'
down_revision = 'fbec71fd9b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_seguimiento_cobro', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('fecha_seguimiento_cobro')

    # ### end Alembic commands ###
