"""Add timezone to Users

Revision ID: 06b26286e397
Revises: 0ca8a381b14d
Create Date: 2026-01-17 12:35:23.220430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b26286e397'
down_revision = '0ca8a381b14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
