"""add follow-up categorization fields to appointment

Revision ID: 083021249e46
Revises: 027b9cb4171d
Create Date: 2026-08-01 01:02:34.560374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083021249e46'
down_revision = '027b9cb4171d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seguimiento_tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('seguimiento_sub', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seguimiento_intento', sa.Integer(), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('seguimiento_intento')
        batch_op.drop_column('seguimiento_sub')
        batch_op.drop_column('seguimiento_tipo')

    # ### end Alembic commands ###
