"""Complete separation of Users and Clients

Revision ID: 08f68ff69e1e
Revises: 26fb19fa17c6
Create Date: 2026-01-24 17:58:04.249905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f68ff69e1e'
down_revision = '26fb19fa17c6'
branch_labels = None
depends_on = None


def drop_foreign_key(batch_op, inspector, table_name, column_name):
    # Encontrar la constraint que corresponde a la columna
    fks = inspector.get_foreign_keys(table_name)
    for fk in fks:
        if column_name in fk['referred_columns'] or column_name in fk['constrained_columns']:
            if fk['name']:
                batch_op.drop_constraint(fk['name'], type_='foreignkey')
            else:
                # Si no tiene nombre, intentamos dropearla por los campos (solo funciona en algunos dialectos en batch)
                # Pero en SQLite con batch_op esto suele funcionar si se pasa None
                batch_op.drop_constraint(None, type_='foreignkey')
            return True
    return False

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if 'clients' table already exists
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'clients' not in tables:
        op.create_table('clients',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=120), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('instagram', sa.String(length=64), nullable=True),
        sa.Column('utm_source', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('assigned_closer_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_closer_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)

    if 'client_comments' not in tables:
        op.create_table('client_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    # Solo dropear si existen
    if 'lead_comments' in tables:
        op.drop_table('lead_comments')
    if 'lead_profiles' in tables:
        op.drop_table('lead_profiles')

    # NOTA: En PostgreSQL no necesitamos batch_op. 
    # En SQLite sí, pero localmente ya hemos hecho "stamp" para saltar este error.
    
    # Para appointments
    columns_appointments = [c['name'] for c in inspector.get_columns('appointments')]
    if 'client_id' not in columns_appointments:
        op.add_column('appointments', sa.Column('client_id', sa.Integer(), nullable=True))
        # Intentar dropear la constraint anónima es difícil en SQL puro sin saber el nombre en Postgres
        # Pero podemos intentar dropear lead_id después de migrar datos (si el usuario lo requiere)
        # Por ahora solo añadimos lo necesario para que Railway no falle por reflexión
        pass

    # Para enrollments
    columns_enrollments = [c['name'] for c in inspector.get_columns('enrollments')]
    if 'client_id' not in columns_enrollments:
        op.add_column('enrollments', sa.Column('client_id', sa.Integer(), nullable=True))

    # Para survey_answers
    columns_survey = [c['name'] for c in inspector.get_columns('survey_answers')]
    if 'client_id' not in columns_survey:
        op.add_column('survey_answers', sa.Column('client_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    pass
