"""Add follow-up funnel stages to SetterDailyStats

Revision ID: 09d9d17d2500
Revises: 36e38bb7d450
Create Date: 2026-04-03 17:38:56.947143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d9d17d2500'
down_revision = '36e38bb7d450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_fu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pain_fu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('offer_fu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agenda_fu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qualification_fur', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pain_fur', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('offer_fur', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agenda_fur', sa.Integer(), nullable=True))
        batch_op.drop_column('follow_up_responded')
        batch_op.drop_column('follow_up_submitted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_up_submitted', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_responded', sa.INTEGER(), nullable=True))
        batch_op.drop_column('agenda_fur')
        batch_op.drop_column('offer_fur')
        batch_op.drop_column('pain_fur')
        batch_op.drop_column('qualification_fur')
        batch_op.drop_column('agenda_fu')
        batch_op.drop_column('offer_fu')
        batch_op.drop_column('pain_fu')
        batch_op.drop_column('qualification_fu')

    # ### end Alembic commands ###
