"""Added TriageTrackerReport

Revision ID: 0bb40704bba5
Revises: cff139f1ae7e
Create Date: 2026-03-18 21:28:04.378636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb40704bba5'
down_revision = 'cff139f1ae7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_tracker_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triage_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starting_1st_call_agendas', sa.Integer(), nullable=True),
    sa.Column('starting_1st_call_confirmando', sa.Integer(), nullable=True),
    sa.Column('starting_1st_call_reprogramando', sa.Integer(), nullable=True),
    sa.Column('starting_1st_call_confirmadas', sa.Integer(), nullable=True),
    sa.Column('starting_1st_call_canceladas', sa.Integer(), nullable=True),
    sa.Column('starting_2nd_call_agendas', sa.Integer(), nullable=True),
    sa.Column('starting_2nd_call_confirmando', sa.Integer(), nullable=True),
    sa.Column('starting_2nd_call_reprogramando', sa.Integer(), nullable=True),
    sa.Column('starting_2nd_call_confirmadas', sa.Integer(), nullable=True),
    sa.Column('starting_2nd_call_canceladas', sa.Integer(), nullable=True),
    sa.Column('all_1st_call_agendas', sa.Integer(), nullable=True),
    sa.Column('all_1st_call_confirmando', sa.Integer(), nullable=True),
    sa.Column('all_1st_call_reprogramando', sa.Integer(), nullable=True),
    sa.Column('all_1st_call_confirmadas', sa.Integer(), nullable=True),
    sa.Column('all_1st_call_canceladas', sa.Integer(), nullable=True),
    sa.Column('all_2nd_call_agendas', sa.Integer(), nullable=True),
    sa.Column('all_2nd_call_confirmando', sa.Integer(), nullable=True),
    sa.Column('all_2nd_call_reprogramando', sa.Integer(), nullable=True),
    sa.Column('all_2nd_call_confirmadas', sa.Integer(), nullable=True),
    sa.Column('all_2nd_call_canceladas', sa.Integer(), nullable=True),
    sa.Column('post_hoy_confirmadas', sa.Integer(), nullable=True),
    sa.Column('post_hoy_ppc_completo', sa.Integer(), nullable=True),
    sa.Column('post_all_confirmadas', sa.Integer(), nullable=True),
    sa.Column('post_all_ppc_completo', sa.Integer(), nullable=True),
    sa.Column('fu_cold_personas_disp_fu', sa.Integer(), nullable=True),
    sa.Column('fu_cold_mjes_realizados', sa.Integer(), nullable=True),
    sa.Column('fu_cold_personas_realizados', sa.Integer(), nullable=True),
    sa.Column('fu_cold_personas_respondidos', sa.Integer(), nullable=True),
    sa.Column('fu_warm_personas_disp_fu', sa.Integer(), nullable=True),
    sa.Column('fu_warm_mjes_realizados', sa.Integer(), nullable=True),
    sa.Column('fu_warm_personas_realizados', sa.Integer(), nullable=True),
    sa.Column('fu_warm_personas_respondidos', sa.Integer(), nullable=True),
    sa.Column('fu_hot_personas_disp_fu', sa.Integer(), nullable=True),
    sa.Column('fu_hot_mjes_realizados', sa.Integer(), nullable=True),
    sa.Column('fu_hot_personas_realizados', sa.Integer(), nullable=True),
    sa.Column('fu_hot_personas_respondidos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triage_tracker_reports')),
    sa.UniqueConstraint('triage_name', 'date', name='_triage_tracker_date_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_tracker_reports')
    # ### end Alembic commands ###
