"""Add CloserDailyStats table

Revision ID: 0ca8a381b14d
Revises: dbaf990ed21c
Create Date: 2026-01-15 22:38:25.915478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca8a381b14d'
down_revision = 'dbaf990ed21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closer_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slots_available', sa.Integer(), nullable=True),
    sa.Column('first_agendas', sa.Integer(), nullable=True),
    sa.Column('first_agendas_attended', sa.Integer(), nullable=True),
    sa.Column('first_agendas_no_show', sa.Integer(), nullable=True),
    sa.Column('first_agendas_rescheduled', sa.Integer(), nullable=True),
    sa.Column('first_agendas_canceled', sa.Integer(), nullable=True),
    sa.Column('second_agendas', sa.Integer(), nullable=True),
    sa.Column('second_agendas_attended', sa.Integer(), nullable=True),
    sa.Column('second_agendas_no_show', sa.Integer(), nullable=True),
    sa.Column('second_agendas_rescheduled', sa.Integer(), nullable=True),
    sa.Column('second_agendas_canceled', sa.Integer(), nullable=True),
    sa.Column('second_calls_booked', sa.Integer(), nullable=True),
    sa.Column('presentations', sa.Integer(), nullable=True),
    sa.Column('sales_on_call', sa.Integer(), nullable=True),
    sa.Column('sales_followup', sa.Integer(), nullable=True),
    sa.Column('followups_started_booking', sa.Integer(), nullable=True),
    sa.Column('followups_started_closing', sa.Integer(), nullable=True),
    sa.Column('replies_booking', sa.Integer(), nullable=True),
    sa.Column('replies_sales', sa.Integer(), nullable=True),
    sa.Column('self_generated_bookings', sa.Integer(), nullable=True),
    sa.Column('notion_completed', sa.Boolean(), nullable=True),
    sa.Column('objection_form_completed', sa.Boolean(), nullable=True),
    sa.Column('win_of_day', sa.Text(), nullable=True),
    sa.Column('improvement_area', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['closer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('closer_id', 'date', name='_closer_date_uc')
    )
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fk_names = [fk.get('name') for fk in inspector.get_foreign_keys('lead_profiles')]
    if 'fk_lead_profiles_assigned_closer_id_users' not in fk_names:
        try:
            with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
                batch_op.create_foreign_key('fk_lead_profiles_assigned_closer_id_users', 'users', ['assigned_closer_id'], ['id'])
        except Exception:
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lead_profiles_assigned_closer_id_users', type_='foreignkey')

    op.drop_table('closer_daily_stats')
    # ### end Alembic commands ###
