"""Add stage_id to Lead

Revision ID: 0d4679c48539
Revises: d6fa5502f1bd
Create Date: 2026-01-30 18:36:17.861697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4679c48539'
down_revision = 'd6fa5502f1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_leads_stage_id_pipeline_stages'), 'pipeline_stages', ['stage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leads_stage_id_pipeline_stages'), type_='foreignkey')
        batch_op.drop_column('stage_id')

    # ### end Alembic commands ###
