"""Added follow ups columns to closer daily report

Revision ID: 0eb530b3d665
Revises: 8c0ecdc20615
Create Date: 2026-03-10 03:10:25.871881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb530b3d665'
down_revision = '8c0ecdc20615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_ups_sent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_replied', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('follow_ups_replied')
        batch_op.drop_column('follow_ups_sent')

    # ### end Alembic commands ###
