"""add id_option and id_question to leadanswer

Revision ID: 0f1edb36526b
Revises: 777workshop123
Create Date: 2026-05-01 00:07:13.394879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1edb36526b'
down_revision = '777workshop123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_option', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('id_question', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_answers', schema=None) as batch_op:
        batch_op.drop_column('id_question')
        batch_op.drop_column('id_option')

    # ### end Alembic commands ###
