"""add event groups

Revision ID: 11d44a12f75e
Revises: 24dca0bd3ed7
Create Date: 2026-01-13 15:21:11.582125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d44a12f75e'
down_revision = '24dca0bd3ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_events_group_id_event_groups', 'event_groups', ['group_id'], ['id'])

    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_survey_questions_event_group_id_event_groups', 'event_groups', ['event_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_survey_questions_event_group_id_event_groups', type_='foreignkey')
        batch_op.drop_column('event_group_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_group_id_event_groups', type_='foreignkey')
        batch_op.drop_column('group_id')

    op.drop_table('event_groups')
    # ### end Alembic commands ###
