"""add associated_id to notifications

Revision ID: 12d53c811fe5
Revises: f8484373db24
Create Date: 2026-02-11 17:14:04.613249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '12d53c811fe5'
down_revision = 'f8484373db24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('associated_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('related_users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_users', sqlite.JSON(), nullable=True))
        batch_op.drop_column('associated_type')
        batch_op.drop_column('associated_id')

    # ### end Alembic commands ###
