"""add question efficacy columns to setter stats

Revision ID: 1401a7cecafc
Revises: f7c11d44e123
Create Date: 2026-04-15 19:47:43.852711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1401a7cecafc'
down_revision = 'f7c11d44e123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_sets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ad_groups_external_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_ad_sets_external_id'), ['external_id'])

    with op.batch_alter_table('manychat_ad_leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_manychat_ad_leads_manychat_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_manychat_ad_leads_ad_id_ads'), type_='foreignkey')

    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q1_useful', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q1_unuseful', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q2_useful', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q2_unuseful', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('q2_unuseful')
        batch_op.drop_column('q2_useful')
        batch_op.drop_column('q1_unuseful')
        batch_op.drop_column('q1_useful')

    with op.batch_alter_table('manychat_ad_leads', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_manychat_ad_leads_ad_id_ads'), 'ads', ['ad_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_manychat_ad_leads_manychat_id'), ['manychat_id'])

    with op.batch_alter_table('ad_sets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ad_sets_external_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_ad_groups_external_id'), ['external_id'])

    # ### end Alembic commands ###
