"""add question efficacy columns to setter stats

Revision ID: 1401a7cecafc
Revises: f7c11d44e123
Create Date: 2026-04-15 19:47:43.852711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1401a7cecafc'
down_revision = 'f7c11d44e123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q1_useful', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q1_unuseful', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q2_useful', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q2_unuseful', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('q2_unuseful')
        batch_op.drop_column('q2_useful')
        batch_op.drop_column('q1_unuseful')
        batch_op.drop_column('q1_useful')

    # ### end Alembic commands ###
