"""Add Event model

Revision ID: 1538d9bfa3aa
Revises: 368d398ea63d
Create Date: 2026-01-13 01:00:54.908986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1538d9bfa3aa'
down_revision = '368d398ea63d'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if not inspector.has_table('events'):
        op.create_table('events',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('utm_source', sa.String(length=64), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name'),
            sa.UniqueConstraint('utm_source')
        )
        
    appt_cols = [c['name'] for c in inspector.get_columns('appointments')]
    if 'event_id' not in appt_cols:
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_appointments_event_id_events', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    op.drop_table('events')
    # ### end Alembic commands ###
