"""add_estado_to_financial_agenda

Revision ID: 164bc2dbe9df
Revises: b2cbbef18715
Create Date: 2026-06-06 13:57:06.746465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164bc2dbe9df'
down_revision = 'b2cbbef18715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=255), server_default='Pendiente', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
