"""Add origin column to appointments and fix schema inconsistencies

Revision ID: 1758951b4a5c
Revises: 490ba91460ba
Create Date: 2026-01-25 06:58:24.975958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1758951b4a5c'
down_revision = '490ba91460ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Para appointments - añadir origin si falta
    columns_appointments = [c['name'] for c in inspector.get_columns('appointments')]
    if 'origin' not in columns_appointments:
        op.add_column('appointments', sa.Column('origin', sa.String(length=100), nullable=True))
    
    if 'client_id' not in columns_appointments:
        op.add_column('appointments', sa.Column('client_id', sa.Integer(), nullable=True))
        # No dropeamos lead_id aquí para evitar riesgos
    
    # Para enrollments
    columns_enrollments = [c['name'] for c in inspector.get_columns('enrollments')]
    if 'client_id' not in columns_enrollments:
        op.add_column('enrollments', sa.Column('client_id', sa.Integer(), nullable=True))

    # Para survey_answers
    columns_survey = [c['name'] for c in inspector.get_columns('survey_answers')]
    if 'client_id' not in columns_survey:
        op.add_column('survey_answers', sa.Column('client_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('step', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('event_group_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'event_groups', ['event_group_id'], ['id'])
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_survey_answers_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['lead_id'], ['id'])
        batch_op.drop_column('client_id')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_programs_name'), type_='unique')

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_pipelines_name'), type_='unique')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payment_methods_name'), type_='unique')

    with op.batch_alter_table('marketing_budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('daily_budget', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('actual_spend', sa.FLOAT(), nullable=True))
        batch_op.drop_column('source')
        batch_op.drop_column('spent')
        batch_op.drop_column('budget')

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_integrations_key'), type_='unique')

    with op.batch_alter_table('google_calendar_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_google_calendar_tokens_user_id'), type_='unique')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_events_utm_source'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_events_name'), type_='unique')

    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funnel_steps', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_event_groups_name'), type_='unique')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_agreed', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_enrollments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])
        batch_op.drop_column('client_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('assigned_closer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_clients_assigned_closer_id_users'), 'users', ['assigned_closer_id'], ['id'])

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_appointments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['lead_id'], ['id'])
        batch_op.drop_column('origin')
        batch_op.drop_column('client_id')

    op.create_table('ads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('total_spend', sa.FLOAT(), nullable=True),
    sa.Column('ad_group_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], name=op.f('fk_ads_ad_group_id')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ads_event_id')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_client_comments_author_id_users')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_comments_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_comments'))
    )
    # ### end Alembic commands ###
