"""Add FinancialSale model

Revision ID: 19b0cff01958
Revises: f81b03cc494e
Create Date: 2026-03-14 15:41:16.578276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b0cff01958'
down_revision = 'f81b03cc494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setter_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_sales'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_sales')
    # ### end Alembic commands ###
