"""add client_id a installment_plans

Revision ID: 1cd1bf9f0ed8
Revises: c174c6b25233
Create Date: 2026-08-05 02:49:34.481184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd1bf9f0ed8'
down_revision = 'c174c6b25233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_installment_plans_client_id'), ['client_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_installment_plans_client_id_clients'), 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_installment_plans_client_id_clients'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_installment_plans_client_id'))
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
