"""Add detailed marketing columns

Revision ID: 226b0fd49b7e
Revises: 3878c7cf0cb7
Create Date: 2026-02-03 15:00:28.630634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226b0fd49b7e'
down_revision = '3878c7cf0cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('conversion_event', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('traffic', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('funnel_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('objective', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('objective')
        batch_op.drop_column('funnel_type')
        batch_op.drop_column('traffic')
        batch_op.drop_column('type')

    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('stage')
        batch_op.drop_column('keyword')

    with op.batch_alter_table('ad_sets', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('conversion_event')
        batch_op.drop_column('audience')

    # ### end Alembic commands ###
