"""add setter_id to event

Revision ID: 237fb3603183
Revises: a56209cfddf1
Create Date: 2026-02-11 14:06:44.049296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237fb3603183'
down_revision = 'a56209cfddf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_events_setter_id_users'), 'users', ['setter_id'], ['id'])
        batch_op.drop_column('redirect_url_success')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirect_url_success', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_events_setter_id_users'), type_='foreignkey')
        batch_op.drop_column('setter_id')

    # ### end Alembic commands ###
