"""Add ad_source and tags to Lead

Revision ID: 24bdb3473819
Revises: 4b1d5cf33b61
Create Date: 2026-01-30 19:21:21.306865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bdb3473819'
down_revision = '4b1d5cf33b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('ad_source')

    # ### end Alembic commands ###
