"""Sync models

Revision ID: 271929187a73
Revises: b72f592453a7
Create Date: 2026-01-21 15:20:18.803581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271929187a73'
down_revision = 'b72f592453a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Appointments Table Checks
    appt_columns = [c['name'] for c in inspector.get_columns('appointments')]
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        if 'google_event_id' not in appt_columns:
            batch_op.add_column(sa.Column('google_event_id', sa.String(length=255), nullable=True))
        if 'presentation_done' not in appt_columns:
            batch_op.add_column(sa.Column('presentation_done', sa.Boolean(), nullable=True))
        if 'is_reschedule' not in appt_columns:
            batch_op.add_column(sa.Column('is_reschedule', sa.Boolean(), nullable=True))
        if 'rescheduled_from_id' not in appt_columns:
            batch_op.add_column(sa.Column('rescheduled_from_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_appointments_rescheduled_from', 'appointments', ['rescheduled_from_id'], ['id'])

    # Closer Stats Table Checks
    stats_columns = [c['name'] for c in inspector.get_columns('closer_daily_stats')]
    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        if 'slots_defined' not in stats_columns:
            batch_op.add_column(sa.Column('slots_defined', sa.Integer(), nullable=True))

    # Enrollments FK Check (Harder to check constraint existence cleanly, but we can check if col exists logic?)
    # closer_id in enrollments likely exists if we are adding FK.
    # We will assume if migration is running, we want to ensure FK.
    # Using try/except block for FK creation is safer if checking constraints is complex.
    # However, create_foreign_key usually doesn't error if it exists? No, it does.
    # Let's inspect constraints.
    enroll_constraints = [c['name'] for c in inspector.get_foreign_keys('enrollments')]
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        # Assuming we named it fk_enrollments_closer or similar, but alembic auto-gen might not have named it consistently unless we provided name.
        # The down_revision implies we are just adding it.
        # If 'closer_id' column exists? It probably existed before? No, `models.py` showed it.
        # Wait, previous models.py didn't show `closer_id` in `Enrollment` column definition?
        # Let's check line 212 of models.py: `closer_id = db.Column(...)`.
        # If migration adds FK, it might imply connection.
        # I'll wrap it safely.
        has_closer_fk = any(fk['referred_table'] == 'users' and 'closer_id' in fk['constrained_columns'] for fk in inspector.get_foreign_keys('enrollments'))
        if not has_closer_fk:
             batch_op.create_foreign_key('fk_enrollments_closer', 'users', ['closer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('slots_defined')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rescheduled_from_id')
        batch_op.drop_column('is_reschedule')
        batch_op.drop_column('presentation_done')
        batch_op.drop_column('google_event_id')

    # ### end Alembic commands ###
