"""Sync models

Revision ID: 271929187a73
Revises: b72f592453a7
Create Date: 2026-01-21 15:20:18.803581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271929187a73'
down_revision = 'b72f592453a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('presentation_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_reschedule', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_from_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appointments_rescheduled_from', 'appointments', ['rescheduled_from_id'], ['id'])

    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots_defined', sa.Integer(), nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_enrollments_closer', 'users', ['closer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('slots_defined')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rescheduled_from_id')
        batch_op.drop_column('is_reschedule')
        batch_op.drop_column('presentation_done')
        batch_op.drop_column('google_event_id')

    # ### end Alembic commands ###
