"""Update AdPeriodSpend

Revision ID: 2801cbf60c67
Revises: d942a9da2664
Create Date: 2026-04-09 14:35:59.901553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2801cbf60c67'
down_revision = 'd942a9da2664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_period_spends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ad_set_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_ad_period_spend'), type_='unique')
        batch_op.create_foreign_key(batch_op.f('fk_ad_period_spends_campaign_id_campaigns'), 'campaigns', ['campaign_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_ad_period_spends_ad_set_id_ad_sets'), 'ad_sets', ['ad_set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_period_spends', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ad_period_spends_ad_set_id_ad_sets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_ad_period_spends_campaign_id_campaigns'), type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('uq_ad_period_spend'), ['ad_id', 'start_date', 'end_date'])
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ad_set_id')
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
