"""Availability use date

Revision ID: 2d024b6fe7c4
Revises: bdfab37cbc21
Create Date: 2026-01-12 22:43:38.546407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d024b6fe7c4'
down_revision = 'bdfab37cbc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.INTEGER(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
