"""Rename AdGroup to AdSet class and add marketing fields

Revision ID: 2d4c7968ae69
Revises: 41e4f0dcf599
Create Date: 2026-02-03 14:24:49.260544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4c7968ae69'
down_revision = '41e4f0dcf599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_ad_groups_external_id'), ['external_id'])

    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_set_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_ads_external_id'), ['external_id'])
        batch_op.drop_constraint(batch_op.f('fk_ads_ad_group_id_ad_groups'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ads_ad_set_id_ad_groups'), 'ad_groups', ['ad_set_id'], ['id'])
        batch_op.drop_column('ad_group_id')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_campaigns_external_id'), ['external_id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funnel_steps', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_events_group_id_event_groups'), 'event_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_group_id_event_groups'), type_='foreignkey')
        batch_op.drop_column('funnel_steps')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_campaigns_external_id'), type_='unique')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_group_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_ads_ad_set_id_ad_groups'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ads_ad_group_id_ad_groups'), 'ad_groups', ['ad_group_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_ads_external_id'), type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('ad_set_id')

    with op.batch_alter_table('ad_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ad_groups_external_id'), type_='unique')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
