"""Add booking fields to LeadProfile

Revision ID: 2dbf3660e6b4
Revises: 2d024b6fe7c4
Create Date: 2026-01-12 23:23:08.785493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbf3660e6b4'
down_revision = '2d024b6fe7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_source', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('years_trying')
        batch_op.drop_column('investment_capacity')
        batch_op.drop_column('academic_stage')
        batch_op.drop_column('needs_financial_support')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_financial_support', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('academic_stage', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('investment_capacity', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('years_trying', sa.INTEGER(), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('status')
        batch_op.drop_column('utm_source')

    # ### end Alembic commands ###
