"""add reflections json to closer daily report

Revision ID: 32015bf9c407
Revises: d3bd603b9829
Create Date: 2026-05-05 22:37:06.531546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32015bf9c407'
down_revision = 'd3bd603b9829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reflections', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('reflections')

    # ### end Alembic commands ###
