"""add sale status column

Revision ID: 331a030d62aa
Revises: f5547202180b
Create Date: 2026-05-29 19:37:23.068535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331a030d62aa'
down_revision = 'f5547202180b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=255), server_default='Completada', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
