"""add calls and reflection fields closer report

Revision ID: 36e38bb7d450
Revises: bf3d8b7a84d9
Create Date: 2026-03-28 16:19:12.268062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e38bb7d450'
down_revision = 'bf3d8b7a84d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_makers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_calls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reflection_victory', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reflection_opportunity', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('reflection_opportunity')
        batch_op.drop_column('reflection_victory')
        batch_op.drop_column('rescheduled_calls')
        batch_op.drop_column('decision_makers')

    # ### end Alembic commands ###
