"""add is_excluded_from_payroll to financial_sales

Revision ID: 3815fdf62b80
Revises: 2aaaf324fb99
Create Date: 2026-07-07 20:05:19.716951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3815fdf62b80'
down_revision = '2aaaf324fb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_excluded_from_payroll', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.drop_column('is_excluded_from_payroll')

    # ### end Alembic commands ###
