"""Initialize enhanced marketing models

Revision ID: 3878c7cf0cb7
Revises: 2d4c7968ae69
Create Date: 2026-02-03 14:30:42.265705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3878c7cf0cb7'
down_revision = '2d4c7968ae69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('campaigns'):
        op.create_table('campaigns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
        sa.UniqueConstraint('external_id', name=op.f('uq_campaigns_external_id'))
        )

    if not inspector.has_table('ad_sets'):
        op.create_table('ad_sets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_ad_sets_campaign_id_campaigns')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_sets')),
        sa.UniqueConstraint('external_id', name=op.f('uq_ad_sets_external_id'))
        )

    if not inspector.has_table('ads'):
        op.create_table('ads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ad_set_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('total_spend', sa.Float(), nullable=True),
        sa.Column('event_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['ad_set_id'], ['ad_sets.id'], name=op.f('fk_ads_ad_set_id_ad_sets')),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ads_event_id_events')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_ads')),
        sa.UniqueConstraint('external_id', name=op.f('uq_ads_external_id'))
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ads')
    op.drop_table('ad_sets')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
