"""add last_contact_outcome and last_contact_at to appointments

Revision ID: 3a05775ef49e
Revises: 796839c55ce8
Create Date: 2026-08-05 12:44:16.636282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a05775ef49e'
down_revision = '796839c55ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_contact_outcome', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_contact_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('last_contact_at')
        batch_op.drop_column('last_contact_outcome')

    # ### end Alembic commands ###
