"""add confirmation_stage, confirmation_contact_status and confirmation_pain_points to appointments

Revision ID: 3a8b192ec920
Revises: e5f6a7b8c9d0
Create Date: 2026-09-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8b192ec920'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_stage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confirmation_contact_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confirmation_pain_points', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('confirmation_pain_points')
        batch_op.drop_column('confirmation_contact_status')
        batch_op.drop_column('confirmation_stage')

    # ### end Alembic commands ###
