"""Add notes to Lead

Revision ID: 41e4f0dcf599
Revises: 24bdb3473819
Create Date: 2026-01-30 19:42:44.993039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e4f0dcf599'
down_revision = '24bdb3473819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
