"""Add event_closers relationship

Revision ID: 420e48ee2e12
Revises: b259a021a6b0
Create Date: 2026-02-10 11:30:38.141898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420e48ee2e12'
down_revision = 'b259a021a6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_closers',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_closers_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_closers_user_id_users')),
    sa.PrimaryKeyConstraint('event_id', 'user_id', name=op.f('pk_event_closers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_closers')
    # ### end Alembic commands ###
