"""add deck workflow fields to appointments

Revision ID: 477538b05ccf
Revises: fdc53a87bd00
Create Date: 2026-05-25 13:48:20.614967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477538b05ccf'
down_revision = 'fdc53a87bd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setter_processed', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('closer_processed', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('setter_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('closer_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ig_chat_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('keyword', sa.String(length=100), nullable=True))

    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('follow_ups_hot_appointments')
        batch_op.drop_column('first_call_sales')
        batch_op.drop_column('follow_ups_cold_sales')
        batch_op.drop_column('second_call_sales')
        batch_op.drop_column('follow_ups_hot_sales')
        batch_op.drop_column('follow_ups_cold_appointments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_ups_cold_appointments', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_hot_sales', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('second_call_sales', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_cold_sales', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('first_call_sales', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_hot_appointments', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('keyword')
        batch_op.drop_column('ig_chat_link')
        batch_op.drop_column('closer_notes')
        batch_op.drop_column('setter_notes')
        batch_op.drop_column('closer_processed')
        batch_op.drop_column('setter_processed')

    # ### end Alembic commands ###
