"""Initial refactor with Clients

Revision ID: 490ba91460ba
Revises: 08f68ff69e1e
Create Date: 2026-01-24 17:59:23.722776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490ba91460ba'
down_revision = '08f68ff69e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_appointments_client_id_clients'), 'clients', ['client_id'], ['id'])
        batch_op.drop_column('lead_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_client_id_clients'), 'clients', ['client_id'], ['id'])
        batch_op.drop_column('student_id')

    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_event_groups_name'), ['name'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_events_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_events_utm_source'), ['utm_source'])

    with op.batch_alter_table('google_calendar_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_google_calendar_tokens_user_id'), ['user_id'])

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_integrations_key'), ['key'])

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_payment_methods_name'), ['name'])

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_programs_name'), ['name'])

    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_survey_answers_client_id_clients'), 'clients', ['client_id'], ['id'])
        batch_op.drop_column('lead_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_survey_answers_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['lead_id'], ['id'])
        batch_op.drop_column('client_id')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_programs_name'), type_='unique')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payment_methods_name'), type_='unique')

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_integrations_key'), type_='unique')

    with op.batch_alter_table('google_calendar_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_google_calendar_tokens_user_id'), type_='unique')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_events_utm_source'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_events_name'), type_='unique')

    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_event_groups_name'), type_='unique')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_enrollments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])
        batch_op.drop_column('client_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_appointments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['lead_id'], ['id'])
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
