"""Initial refactor with Clients

Revision ID: 490ba91460ba
Revises: 08f68ff69e1e
Create Date: 2026-01-24 17:59:23.722776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490ba91460ba'
down_revision = '08f68ff69e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Para appointments
    columns_appointments = [c['name'] for c in inspector.get_columns('appointments')]
    if 'client_id' not in columns_appointments:
        op.add_column('appointments', sa.Column('client_id', sa.Integer(), nullable=True))
        # No dropeamos lead_id aquí para evitar el IndexError en Postgres
    
    # Para enrollments
    columns_enrollments = [c['name'] for c in inspector.get_columns('enrollments')]
    if 'client_id' not in columns_enrollments:
        op.add_column('enrollments', sa.Column('client_id', sa.Integer(), nullable=True))

    # Unique constraints - solo si no existen
    # (En Postgres/Railway a veces fallan si ya están)
    
    # Note: simplify unique constraint creation
    def add_uq(table, name, cols):
        try:
            op.create_unique_constraint(op.f(name), table, cols)
        except Exception:
            pass

    add_uq('event_groups', 'uq_event_groups_name', ['name'])
    add_uq('events', 'uq_events_name', ['name'])
    add_uq('events', 'uq_events_utm_source', ['utm_source'])
    add_uq('google_calendar_tokens', 'uq_google_calendar_tokens_user_id', ['user_id'])
    add_uq('integrations', 'uq_integrations_key', ['key'])
    add_uq('payment_methods', 'uq_payment_methods_name', ['name'])
    add_uq('programs', 'uq_programs_name', ['name'])

    # Para survey_answers
    columns_survey = [c['name'] for c in inspector.get_columns('survey_answers')]
    if 'client_id' not in columns_survey:
        op.add_column('survey_answers', sa.Column('client_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_survey_answers_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['lead_id'], ['id'])
        batch_op.drop_column('client_id')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_programs_name'), type_='unique')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payment_methods_name'), type_='unique')

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_integrations_key'), type_='unique')

    with op.batch_alter_table('google_calendar_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_google_calendar_tokens_user_id'), type_='unique')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_events_utm_source'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_events_name'), type_='unique')

    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_event_groups_name'), type_='unique')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_enrollments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])
        batch_op.drop_column('client_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_appointments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['lead_id'], ['id'])
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
