"""add offer and link openings

Revision ID: 49256092400d
Revises: 566a975790f5
Create Date: 2026-06-25 18:44:34.703718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49256092400d'
down_revision = '566a975790f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_opening_submitted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('offer_opening_responded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('link_opening_submitted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('link_opening_responded', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('link_opening_responded')
        batch_op.drop_column('link_opening_submitted')
        batch_op.drop_column('offer_opening_responded')
        batch_op.drop_column('offer_opening_submitted')

    # ### end Alembic commands ###
