"""Sync financial models with Google Sheets fields

Revision ID: 493c095f5bfa
Revises: cd24f91644eb
Create Date: 2026-04-12 12:27:29.206939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493c095f5bfa'
down_revision = 'cd24f91644eb'
branch_labels = None
depends_on = None


def upgrade():
    # financial_agendas: agregar nuevas columnas
    op.add_column('financial_agendas', sa.Column('nombre', sa.String(length=150), nullable=True))
    op.add_column('financial_agendas', sa.Column('registro', sa.String(length=100), nullable=True))
    op.add_column('financial_agendas', sa.Column('fecha_meet', sa.String(length=100), nullable=True))
    op.add_column('financial_agendas', sa.Column('whatsapp', sa.String(length=50), nullable=True))
    op.add_column('financial_agendas', sa.Column('zona_geografica', sa.String(length=100), nullable=True))
    op.add_column('financial_agendas', sa.Column('closer', sa.String(length=100), nullable=True))
    op.add_column('financial_agendas', sa.Column('lead', sa.String(length=100), nullable=True))
    op.add_column('financial_agendas', sa.Column('mail', sa.String(length=150), nullable=True))
    op.add_column('financial_agendas', sa.Column('created_at', sa.DateTime(), nullable=True))

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # financial_agendas: eliminar columnas viejas (solo si existen)
    fa_cols = [c['name'] for c in inspector.get_columns('financial_agendas')]
    for col in ['status', 'setter_name', 'error_notes', 'client_name', 'closer_name']:
        if col in fa_cols:
            op.drop_column('financial_agendas', col)
    # Nota: NO eliminamos 'date' aquí, la siguiente migración la re-agrega

    # financial_sales: agregar nuevas columnas
    op.add_column('financial_sales', sa.Column('email_vendedor', sa.String(length=150), nullable=True))
    op.add_column('financial_sales', sa.Column('nombre_cliente', sa.String(length=150), nullable=True))
    op.add_column('financial_sales', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('financial_sales', sa.Column('mail_cliente', sa.String(length=150), nullable=True))
    op.add_column('financial_sales', sa.Column('tipo_pago', sa.String(length=100), nullable=True))
    op.add_column('financial_sales', sa.Column('monto', sa.Float(), nullable=True))
    op.add_column('financial_sales', sa.Column('segundo_pago', sa.String(length=100), nullable=True))
    op.add_column('financial_sales', sa.Column('metodo_pago', sa.String(length=100), nullable=True))
    op.add_column('financial_sales', sa.Column('examen', sa.String(length=100), nullable=True))
    op.add_column('financial_sales', sa.Column('setter', sa.String(length=100), nullable=True))
    op.add_column('financial_sales', sa.Column('created_at', sa.DateTime(), nullable=True))

    # financial_sales: eliminar columnas viejas (solo si existen)
    fs_cols = [c['name'] for c in inspector.get_columns('financial_sales')]
    for col in ['product', 'status', 'setter_name', 'payment_type', 'error_notes', 'amount']:
        if col in fs_cols:
            op.drop_column('financial_sales', col)




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('error_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('setter_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'valid'"), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('product', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('setter')
        batch_op.drop_column('examen')
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('segundo_pago')
        batch_op.drop_column('monto')
        batch_op.drop_column('tipo_pago')
        batch_op.drop_column('mail_cliente')
        batch_op.drop_column('telefono')
        batch_op.drop_column('nombre_cliente')
        batch_op.drop_column('email_vendedor')

    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closer_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('client_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('error_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('setter_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('mail')
        batch_op.drop_column('lead')
        batch_op.drop_column('closer')
        batch_op.drop_column('zona_geografica')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('fecha_meet')
        batch_op.drop_column('registro')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
