"""add_examen_to_appointment

Revision ID: 52504b1906e7
Revises: 331a030d62aa
Create Date: 2026-06-02 20:44:39.544222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52504b1906e7'
down_revision = '331a030d62aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examen', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('examen')

    # ### end Alembic commands ###
