"""add_encargado_triage_and_triage_role

Revision ID: 53f9fe03fb96
Revises: 5698639b3a7d
Create Date: 2026-06-15 22:23:58.488737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f9fe03fb96'
down_revision = '5698639b3a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encargado_triage', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.drop_column('encargado_triage')

    # ### end Alembic commands ###
