"""add_survey_mapping_fields

Revision ID: 541920fb0590
Revises: 11d44a12f75e
Create Date: 2026-01-13 16:02:40.456407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541920fb0590'
down_revision = '11d44a12f75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_field', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('step', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_column('step')
        batch_op.drop_column('mapping_field')

    # ### end Alembic commands ###
