"""add decision maker and sold in call fields

Revision ID: 566a975790f5
Revises: fcdeb1157b85
Create Date: 2026-06-24 20:10:03.038074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566a975790f5'
down_revision = 'fcdeb1157b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('with_decision_maker', sa.Boolean(), nullable=True))

    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_in_call', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.drop_column('sold_in_call')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('with_decision_maker')

    # ### end Alembic commands ###
