"""add_finance_view_models

Revision ID: 5698639b3a7d
Revises: a71f374b6911
Create Date: 2026-06-08 15:49:57.620768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5698639b3a7d'
down_revision = 'a71f374b6911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_payment_method_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('payment_method', sa.String(length=255), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_payment_method_balances')),
    sa.UniqueConstraint('month', 'payment_method', name='_month_pm_uc')
    )
    op.create_table('monthly_savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('savings', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_savings')),
    sa.UniqueConstraint('month', name=op.f('uq_monthly_savings_month'))
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('salary_type', sa.String(length=50), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members'))
    )
    op.create_table('monthly_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('commissions', sa.Float(), nullable=True),
    sa.Column('bonuses', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['team_members.id'], name=op.f('fk_monthly_payroll_member_id_team_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_payroll'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_finance', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_view_finance')

    op.drop_table('monthly_payroll')
    op.drop_table('team_members')
    op.drop_table('monthly_savings')
    op.drop_table('monthly_payment_method_balances')
    # ### end Alembic commands ###
