"""Add answers JSON to setter_daily_stats

Revision ID: 590aa8f7d8f8
Revises: 694c0716358a
Create Date: 2026-02-12 11:04:35.990117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590aa8f7d8f8'
down_revision = '694c0716358a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('answers')

    # ### end Alembic commands ###
