"""add total_amount to clients

Revision ID: 5d084533d803
Revises: 1cd1bf9f0ed8
Create Date: 2026-08-05 10:50:32.122229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d084533d803'
down_revision = '1cd1bf9f0ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
