"""add hot and cold followups to closer

Revision ID: 5dea270e5e8a
Revises: 0eb530b3d665
Create Date: 2026-03-10 12:34:13.515966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dea270e5e8a'
down_revision = '0eb530b3d665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_ups_hot_sent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_hot_replied', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_cold_sent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_cold_replied', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('follow_ups_cold_replied')
        batch_op.drop_column('follow_ups_cold_sent')
        batch_op.drop_column('follow_ups_hot_replied')
        batch_op.drop_column('follow_ups_hot_sent')

    # ### end Alembic commands ###
