"""add installment plan model

Revision ID: 649861242f3c
Revises: 083021249e46
Create Date: 2026-08-01 01:42:21.481170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649861242f3c'
down_revision = '083021249e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_installment_plans_appointment_id_appointments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_plans'))
    )
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installment_plans_appointment_id'), ['appointment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installment_plans_appointment_id'))

    op.drop_table('installment_plans')
    # ### end Alembic commands ###
