"""Remove redundant columns from setter_daily_stats

Revision ID: 64d023e5e539
Revises: 590aa8f7d8f8
Create Date: 2026-02-12 11:16:29.507338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d023e5e539'
down_revision = '590aa8f7d8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('new_offers')
        batch_op.drop_column('appointments_booked')
        batch_op.drop_column('follow_ups')
        batch_op.drop_column('inbound_leads')
        batch_op.drop_column('links_sent')
        batch_op.drop_column('openings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openings', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('links_sent', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('inbound_leads', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('appointments_booked', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('new_offers', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
