"""add_comment_notifications

Revision ID: 6603914498e0
Revises: a8be502f5e26
Create Date: 2026-07-16 00:55:02.044667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6603914498e0'
down_revision = 'a8be502f5e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_comment_notifications_client_id_clients')),
    sa.ForeignKeyConstraint(['comment_id'], ['client_comments.id'], name=op.f('fk_comment_notifications_comment_id_client_comments')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_comment_notifications_sender_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comment_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_notifications'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_notifications')
    # ### end Alembic commands ###
