"""add timezone to users

Revision ID: 68520c08d44f
Revises: 06b26286e397
Create Date: 2026-01-17 13:00:01.961445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68520c08d44f'
down_revision = '06b26286e397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('start_time',
                existing_type=sa.DATETIME(),
                nullable=True)
        batch_op.create_index(batch_op.f('ix_appointments_start_time'), ['start_time'], unique=False)

    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('role')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_start_time'))
        batch_op.alter_column('start_time',
                existing_type=sa.DATETIME(),
                nullable=False)

    # ### end Alembic commands ###
