"""add_follow_up_fields_to_financial_agenda

Revision ID: 686f8945d822
Revises: 6603914498e0
Create Date: 2026-07-20 11:49:12.471854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686f8945d822'
down_revision = '6603914498e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_seguimiento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seguimiento_realizado', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.drop_column('seguimiento_realizado')
        batch_op.drop_column('fecha_seguimiento')

    # ### end Alembic commands ###
