"""Add TriageDailyReport model

Revision ID: 693d6daeeec8
Revises: 19b0cff01958
Create Date: 2026-03-15 15:56:28.745716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693d6daeeec8'
down_revision = '19b0cff01958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triage_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('agendas_nuevas', sa.Integer(), nullable=True),
    sa.Column('agendas_confirmadas', sa.Integer(), nullable=True),
    sa.Column('asistencias', sa.Integer(), nullable=True),
    sa.Column('cancelaciones', sa.Integer(), nullable=True),
    sa.Column('reprogramandos', sa.Integer(), nullable=True),
    sa.Column('no_shows', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['triage_id'], ['users.id'], name=op.f('fk_triage_daily_reports_triage_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triage_daily_reports')),
    sa.UniqueConstraint('triage_id', 'date', name='_triage_report_date_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_daily_reports')
    # ### end Alembic commands ###
