"""Refactor setter stats to single table

Revision ID: 694c0716358a
Revises: c17ee28580ce
Create Date: 2026-02-12 03:02:56.206123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694c0716358a'
down_revision = 'c17ee28580ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setter_daily_stage_metrics')
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_1_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stage_2_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stage_3_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stage_4_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stage_5_value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('stage_5_value')
        batch_op.drop_column('stage_4_value')
        batch_op.drop_column('stage_3_value')
        batch_op.drop_column('stage_2_value')
        batch_op.drop_column('stage_1_value')

    op.create_table('setter_daily_stage_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('daily_stats_id', sa.INTEGER(), nullable=False),
    sa.Column('stage_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['daily_stats_id'], ['setter_daily_stats.id'], name=op.f('fk_setter_daily_stage_metrics_daily_stats_id_setter_daily_stats')),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], name=op.f('fk_setter_daily_stage_metrics_stage_id_pipeline_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setter_daily_stage_metrics')),
    sa.UniqueConstraint('daily_stats_id', 'stage_id', name=op.f('_setter_daily_stage_uc'))
    )
    # ### end Alembic commands ###
