"""restore_survey_event_relation

Revision ID: 6a4038ba886e
Revises: 7466a8a74c9e
Create Date: 2026-01-25 20:09:36.701102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4038ba886e'
down_revision = '7466a8a74c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('step', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_survey_questions_event_id_events'), 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_survey_questions_event_id_events'), type_='foreignkey')
        batch_op.drop_column('step')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
