"""standardize_financial_models

Revision ID: 6b97d0358ed0
Revises: 493c095f5bfa
Create Date: 2026-04-12 14:28:08.235564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b97d0358ed0'
down_revision = '493c095f5bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
