"""Agrega FeatureToggle para auditoria de leads de closers

Revision ID: 6be4ac5883e0
Revises: 772f47fdf24d
Create Date: 2026-08-10 20:35:30.204584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be4ac5883e0'
down_revision = '772f47fdf24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_toggles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_feature_toggles_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_toggles')),
    sa.UniqueConstraint('key', name=op.f('uq_feature_toggles_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_toggles')
    # ### end Alembic commands ###
