"""add reflections json to closer daily stats

Revision ID: 72c54d32ddf5
Revises: 32015bf9c407
Create Date: 2026-05-05 22:39:49.451031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c54d32ddf5'
down_revision = '32015bf9c407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reflections', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('reflections')

    # ### end Alembic commands ###
