"""add_timezone_fix

Revision ID: 7466a8a74c9e
Revises: 1758951b4a5c
Create Date: 2026-01-25 19:27:02.442284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7466a8a74c9e'
down_revision = '1758951b4a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('marketing_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('spent', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketing_budgets'))
    )
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipelines')),
    sa.UniqueConstraint('name', name=op.f('uq_pipelines_name'))
    )
    op.create_table('ad_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_ad_groups_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_groups'))
    )
    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_stages_pipeline_id_pipelines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stages'))
    )
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_spend', sa.Float(), nullable=True),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], name=op.f('fk_ads_ad_group_id_ad_groups')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ads_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ads'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_appointments_lead_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appointments_event_id_events'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appointments_rescheduled_from'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_appointments_client_id_clients'), 'clients', ['client_id'], ['id'])
        batch_op.drop_column('presentation_done')
        batch_op.drop_column('rescheduled_from_id')
        batch_op.drop_column('is_reschedule')
        batch_op.drop_column('google_event_id')
        batch_op.drop_column('event_id')
        batch_op.drop_column('lead_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clients_assigned_closer_id_users'), type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('notes')
        batch_op.drop_column('utm_source')
        batch_op.drop_column('assigned_closer_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_enrollments_student_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_client_id_clients'), 'clients', ['client_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('student_id')
        batch_op.drop_column('total_agreed')

    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.drop_column('funnel_steps')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('redirect_url_fail', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('redirect_url_success', sa.String(length=255), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('reference_id')

    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_survey_answers_lead_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_survey_answers_client_id_clients'), 'clients', ['client_id'], ['id'])
        batch_op.drop_column('lead_id')

    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_survey_questions_event_group_id_event_groups'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_survey_questions_event_id_events'), type_='foreignkey')
        batch_op.drop_column('event_group_id')
        batch_op.drop_column('step')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('step', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('event_group_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_survey_questions_event_id_events'), 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_survey_questions_event_group_id_event_groups'), 'event_groups', ['event_group_id'], ['id'])

    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_survey_answers_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_survey_answers_lead_id_users'), 'users', ['lead_id'], ['id'])
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('redirect_url_success')
        batch_op.drop_column('redirect_url_fail')
        batch_op.drop_column('min_score')

    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funnel_steps', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_agreed', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_enrollments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_student_id_users'), 'users', ['student_id'], ['id'])
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_closer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_clients_assigned_closer_id_users'), 'users', ['assigned_closer_id'], ['id'])

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('google_event_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_reschedule', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_from_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('presentation_done', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_appointments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_appointments_rescheduled_from'), 'appointments', ['rescheduled_from_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_event_id_events'), 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_lead_id_users'), 'users', ['lead_id'], ['id'])
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('ads')
    op.drop_table('pipeline_stages')
    op.drop_table('ad_groups')
    op.drop_table('pipelines')
    op.drop_table('marketing_budgets')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
