"""add_timezone_fix

Revision ID: 7466a8a74c9e
Revises: 1758951b4a5c
Create Date: 2026-01-25 19:27:02.442284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7466a8a74c9e'
down_revision = '1758951b4a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Tables to inspect
    tables_to_check = ['appointments', 'clients', 'enrollments', 'survey_answers', 'survey_questions']
    existing_fks = {}
    existing_cols = {}
    
    for table in tables_to_check:
        try:
            existing_fks[table] = [fk['name'] for fk in inspector.get_foreign_keys(table) if fk['name']]
            existing_cols[table] = [c['name'] for c in inspector.get_columns(table)]
        except:
            existing_fks[table] = []
            existing_cols[table] = []

    # Create tables (KEEP AS IS)
    if 'campaigns' not in inspector.get_table_names():
        op.create_table('campaigns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
        )
    if 'marketing_budgets' not in inspector.get_table_names():
        op.create_table('marketing_budgets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('budget', sa.Float(), nullable=True),
        sa.Column('spent', sa.Float(), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_marketing_budgets'))
        )
    if 'pipelines' not in inspector.get_table_names():
        op.create_table('pipelines',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipelines')),
        sa.UniqueConstraint('name', name=op.f('uq_pipelines_name'))
        )
    if 'ad_groups' not in inspector.get_table_names():
        op.create_table('ad_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_ad_groups_campaign_id_campaigns')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_groups'))
        )
    if 'pipeline_stages' not in inspector.get_table_names():
        op.create_table('pipeline_stages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pipeline_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_stages_pipeline_id_pipelines')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stages'))
        )
    if 'ads' not in inspector.get_table_names():
        op.create_table('ads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('total_spend', sa.Float(), nullable=True),
        sa.Column('ad_group_id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], name=op.f('fk_ads_ad_group_id_ad_groups')),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ads_event_id_events')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_ads'))
        )
        
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        if 'client_id' in existing_cols['appointments']:
            batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=False)
            
        if 'fk_appointments_lead_id_users' in existing_fks['appointments']:
            batch_op.drop_constraint(batch_op.f('fk_appointments_lead_id_users'), type_='foreignkey')
        if 'fk_appointments_event_id_events' in existing_fks['appointments']:
            batch_op.drop_constraint(batch_op.f('fk_appointments_event_id_events'), type_='foreignkey')
        if 'fk_appointments_rescheduled_from' in existing_fks['appointments']:
            batch_op.drop_constraint(batch_op.f('fk_appointments_rescheduled_from'), type_='foreignkey')
            
        # Check if FK to clients exists to avoid dupe? Usually create_foreign_key names it. 
        # If we use explicit name, we can check. 
        # op.f returns the naming convention name.
        # Let's assumes if client_id exists we want strict FK.
        # batch_op.create_foreign_key(...) 
        # Safe to run usually if it doesn't exist, but duplication might error. 
        # For now, let's leave create_foreign_key as implicit/standard unless it errors uniquely. 
        # The errors were about DROPPING non-existent ones.
        batch_op.create_foreign_key(batch_op.f('fk_appointments_client_id_clients'), 'clients', ['client_id'], ['id'])
        
        for col in ['presentation_done', 'rescheduled_from_id', 'is_reschedule', 'google_event_id', 'event_id', 'lead_id']:
            if col in existing_cols['appointments']:
                batch_op.drop_column(col)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        if 'fk_clients_assigned_closer_id_users' in existing_fks['clients']:
            batch_op.drop_constraint(batch_op.f('fk_clients_assigned_closer_id_users'), type_='foreignkey')
        
        for col in ['status', 'notes', 'utm_source', 'assigned_closer_id']:
            if col in existing_cols['clients']:
                batch_op.drop_column(col)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        if 'client_id' in existing_cols['enrollments']:
            batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=False)
            
        if 'fk_enrollments_student_id_users' in existing_fks['enrollments']:
            batch_op.drop_constraint(batch_op.f('fk_enrollments_student_id_users'), type_='foreignkey')
            
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_client_id_clients'), 'clients', ['client_id'], ['id'])
        
        for col in ['status', 'student_id', 'total_agreed']:
            if col in existing_cols['enrollments']:
                batch_op.drop_column(col)

    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        # Check columns
        insp_cols = [c['name'] for c in inspector.get_columns('event_groups')]
        if 'funnel_steps' in insp_cols:
            batch_op.drop_column('funnel_steps')

    with op.batch_alter_table('events', schema=None) as batch_op:
        insp_cols = [c['name'] for c in inspector.get_columns('events')]
        if 'min_score' not in insp_cols:
            batch_op.add_column(sa.Column('min_score', sa.Integer(), nullable=True))
        if 'redirect_url_fail' not in insp_cols:
            batch_op.add_column(sa.Column('redirect_url_fail', sa.String(length=255), nullable=True))
        if 'redirect_url_success' not in insp_cols:
            batch_op.add_column(sa.Column('redirect_url_success', sa.String(length=255), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        insp_cols = [c['name'] for c in inspector.get_columns('payments')]
        if 'transaction_id' in insp_cols: batch_op.drop_column('transaction_id')
        if 'reference_id' in insp_cols: batch_op.drop_column('reference_id')

    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        if 'client_id' in existing_cols['survey_answers']:
            batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=False)
        
        if 'fk_survey_answers_lead_id_users' in existing_fks['survey_answers']:
            batch_op.drop_constraint(batch_op.f('fk_survey_answers_lead_id_users'), type_='foreignkey')
            
        batch_op.create_foreign_key(batch_op.f('fk_survey_answers_client_id_clients'), 'clients', ['client_id'], ['id'])
        
        if 'lead_id' in existing_cols['survey_answers']:
            batch_op.drop_column('lead_id')

    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        if 'fk_survey_questions_event_group_id_event_groups' in existing_fks['survey_questions']:
            batch_op.drop_constraint(batch_op.f('fk_survey_questions_event_group_id_event_groups'), type_='foreignkey')
        if 'fk_survey_questions_event_id_events' in existing_fks['survey_questions']:
            batch_op.drop_constraint(batch_op.f('fk_survey_questions_event_id_events'), type_='foreignkey')
            
        for col in ['event_group_id', 'step', 'event_id']:
            if col in existing_cols['survey_questions']:
                batch_op.drop_column(col)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('step', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('event_group_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_survey_questions_event_id_events'), 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_survey_questions_event_group_id_event_groups'), 'event_groups', ['event_group_id'], ['id'])

    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_survey_answers_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_survey_answers_lead_id_users'), 'users', ['lead_id'], ['id'])
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('redirect_url_success')
        batch_op.drop_column('redirect_url_fail')
        batch_op.drop_column('min_score')

    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funnel_steps', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_agreed', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_enrollments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_student_id_users'), 'users', ['student_id'], ['id'])
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_closer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_clients_assigned_closer_id_users'), 'users', ['assigned_closer_id'], ['id'])

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('google_event_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_reschedule', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_from_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('presentation_done', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_appointments_client_id_clients'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_appointments_rescheduled_from'), 'appointments', ['rescheduled_from_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_event_id_events'), 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_lead_id_users'), 'users', ['lead_id'], ['id'])
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('ads')
    op.drop_table('pipeline_stages')
    op.drop_table('ad_groups')
    op.drop_table('pipelines')
    op.drop_table('marketing_budgets')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
