"""add programa_code to installment_plans

Revision ID: 75aea94ff0e5
Revises: 0995e4725f90
Create Date: 2026-08-06 02:33:04.746581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aea94ff0e5'
down_revision = '0995e4725f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('programa_code', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_installment_plans_programa_code'), ['programa_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installment_plans_programa_code'))
        batch_op.drop_column('programa_code')

    # ### end Alembic commands ###
