"""add srd hot cold scheduled and referrals metrics

Revision ID: 7648b2670011
Revises: f83ef7f1cc72
Create Date: 2026-07-02 11:05:14.287051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7648b2670011'
down_revision = 'f83ef7f1cc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_ups_hot_scheduled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_cold_scheduled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referrals_sourced', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referrals_contacted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referrals_scheduled', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('referrals_scheduled')
        batch_op.drop_column('referrals_contacted')
        batch_op.drop_column('referrals_sourced')
        batch_op.drop_column('follow_ups_cold_scheduled')
        batch_op.drop_column('follow_ups_hot_scheduled')

    # ### end Alembic commands ###
