"""add followup_reminder_sent_pm_at to appointments

Revision ID: 772f47fdf24d
Revises: ca66e36b5bca
Create Date: 2026-08-06 20:55:52.212082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772f47fdf24d'
down_revision = 'ca66e36b5bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followup_reminder_sent_pm_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('followup_reminder_sent_pm_at')

    # ### end Alembic commands ###
