"""add workshop system consolidated

Revision ID: 777workshop123
Revises: 1401a7cecafc
Create Date: 2026-04-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777workshop123'
down_revision = '1401a7cecafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_templates')),
    sa.UniqueConstraint('external_id', name=op.f('uq_workshop_templates_external_id'))
    )
    op.create_table('workshop_buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workshop_templates.id'], name=op.f('fk_workshop_buttons_template_id_workshop_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_buttons'))
    )
    op.create_table('workshop_template_sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workshop_templates.id'], name=op.f('fk_workshop_template_sends_template_id_workshop_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_template_sends')),
    sa.UniqueConstraint('template_id', 'date', name='_template_date_uc')
    )
    op.create_table('workshop_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('button_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['button_id'], ['workshop_buttons.id'], name=op.f('fk_workshop_interactions_button_id_workshop_buttons')),
    sa.ForeignKeyConstraint(['lead_id'], ['manychat_leads.id'], name=op.f('fk_workshop_interactions_lead_id_manychat_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_interactions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_interactions')
    op.drop_table('workshop_template_sends')
    op.drop_table('workshop_buttons')
    op.drop_table('workshop_templates')
    # ### end Alembic commands ###
