"""add grupo to clients and financial_agendas

Revision ID: 796839c55ce8
Revises: 5d084533d803
Create Date: 2026-08-05 12:20:01.323317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796839c55ce8'
down_revision = '5d084533d803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo', sa.String(length=50), nullable=True))

    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_agendas', schema=None) as batch_op:
        batch_op.drop_column('grupo')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('grupo')

    # ### end Alembic commands ###
