"""add_dolores_to_client

Revision ID: 7f63f07d9384
Revises: 53f9fe03fb96
Create Date: 2026-06-15 22:37:59.699071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f63f07d9384'
down_revision = '53f9fe03fb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dolores', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('dolores')

    # ### end Alembic commands ###
