"""add_form_data_to_client

Revision ID: 80c788051ebb
Revises: d8a198cbb274
Create Date: 2026-06-17 15:01:27.708620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c788051ebb'
down_revision = 'd8a198cbb274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('form_data')

    # ### end Alembic commands ###
