"""add lead event log history model

Revision ID: 875aef993f18
Revises: da0c8ee3507e
Create Date: 2026-05-25 19:27:41.713179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875aef993f18'
down_revision = 'da0c8ee3507e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_lead_event_logs_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lead_event_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_event_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_event_logs')
    # ### end Alembic commands ###
