"""Update triage report fields

Revision ID: 8be8fdeb9fdd
Revises: edfbc2b017ba
Create Date: 2026-03-16 18:46:13.414594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be8fdeb9fdd'
down_revision = 'edfbc2b017ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_contestan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seguimientos_iniciados', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seguimientos_contestados', sa.Integer(), nullable=True))
        batch_op.drop_column('asistencias')
        batch_op.drop_column('no_shows')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_shows', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('asistencias', sa.INTEGER(), nullable=True))
        batch_op.drop_column('seguimientos_contestados')
        batch_op.drop_column('seguimientos_iniciados')
        batch_op.drop_column('no_contestan')

    # ### end Alembic commands ###
