"""Refactor closer_daily_reports: single slots and offers_made

Revision ID: 8c0ecdc20615
Revises: 9637d1ee22ff
Create Date: 2026-03-10 01:31:35.417764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0ecdc20615'
down_revision = '9637d1ee22ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('offers_made', sa.Integer(), nullable=True))
        batch_op.drop_column('first_call_slots')
        batch_op.drop_column('second_call_slots')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_call_slots', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('first_call_slots', sa.INTEGER(), nullable=True))
        batch_op.drop_column('offers_made')
        batch_op.drop_column('slots')

    # ### end Alembic commands ###
