"""Add closer_daily_reports table

Revision ID: 9637d1ee22ff
Revises: e398e0e02d0c
Create Date: 2026-03-09 17:58:30.238507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9637d1ee22ff'
down_revision = 'e398e0e02d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closer_daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('first_call_slots', sa.Integer(), nullable=True),
    sa.Column('first_call_scheduled', sa.Integer(), nullable=True),
    sa.Column('first_call_attended', sa.Integer(), nullable=True),
    sa.Column('first_call_no_show', sa.Integer(), nullable=True),
    sa.Column('first_call_rescheduled', sa.Integer(), nullable=True),
    sa.Column('first_call_canceled', sa.Integer(), nullable=True),
    sa.Column('second_call_slots', sa.Integer(), nullable=True),
    sa.Column('second_call_scheduled', sa.Integer(), nullable=True),
    sa.Column('second_call_attended', sa.Integer(), nullable=True),
    sa.Column('second_call_no_show', sa.Integer(), nullable=True),
    sa.Column('second_call_rescheduled', sa.Integer(), nullable=True),
    sa.Column('second_call_canceled', sa.Integer(), nullable=True),
    sa.Column('pif_count', sa.Integer(), nullable=True),
    sa.Column('pif_cash_collected', sa.Float(), nullable=True),
    sa.Column('pif_in_call_count', sa.Integer(), nullable=True),
    sa.Column('pif_in_call_cash', sa.Float(), nullable=True),
    sa.Column('split_count', sa.Integer(), nullable=True),
    sa.Column('split_cash_collected', sa.Float(), nullable=True),
    sa.Column('split_in_call_count', sa.Integer(), nullable=True),
    sa.Column('split_in_call_cash', sa.Float(), nullable=True),
    sa.Column('deposit_count', sa.Integer(), nullable=True),
    sa.Column('deposit_cash_collected', sa.Float(), nullable=True),
    sa.Column('deposit_in_call_count', sa.Integer(), nullable=True),
    sa.Column('deposit_in_call_cash', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['closer_id'], ['users.id'], name=op.f('fk_closer_daily_reports_closer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_closer_daily_reports')),
    sa.UniqueConstraint('closer_id', 'date', name='_closer_report_date_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('closer_daily_reports')
    # ### end Alembic commands ###
