"""Add is_pinned to Appointment

Revision ID: 99678e983258
Revises: 950a7d25f7aa
Create Date: 2026-01-22 13:29:32.064179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99678e983258'
down_revision = '950a7d25f7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
