"""Add full_name to lead_profile

Revision ID: 9dfdeb3e0e94
Revises: 9899c7499683
Create Date: 2026-01-24 11:01:54.719800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfdeb3e0e94'
down_revision = '9899c7499683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
