"""Remove unwanted fields from appointment model

Revision ID: a10308b8384e
Revises: 96674e00d720
Create Date: 2026-02-07 11:36:59.428164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10308b8384e'
down_revision = '96674e00d720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_rescheduled_from_id_appointments'), type_='foreignkey')
        batch_op.drop_column('appointment_type')
        batch_op.drop_column('is_reschedule')
        batch_op.drop_column('status')
        batch_op.drop_column('rescheduled_from_id')
        batch_op.drop_column('presentation_done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presentation_done', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_from_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_reschedule', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('appointment_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_rescheduled_from_id_appointments'), 'appointments', ['rescheduled_from_id'], ['id'])

    # ### end Alembic commands ###
