"""add follow_up_status to client

Revision ID: a4c31a66f9b4
Revises: 7648b2670011
Create Date: 2026-07-03 12:57:59.410151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c31a66f9b4'
down_revision = '7648b2670011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_up_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('follow_up_status')

    # ### end Alembic commands ###
