"""Add two_chat_number to User model

Revision ID: a56209cfddf1
Revises: 245daed93cd2
Create Date: 2026-02-10 20:16:34.605869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56209cfddf1'
down_revision = '245daed93cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_chat_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_chat_number')

    # ### end Alembic commands ###
