"""add_objeciones_to_client

Revision ID: a71f374b6911
Revises: 164bc2dbe9df
Create Date: 2026-06-08 14:49:20.949680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71f374b6911'
down_revision = '164bc2dbe9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objeciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('observaciones')
        batch_op.drop_column('objeciones')

    # ### end Alembic commands ###
