"""add_stage_specific_metrics_to_setter_report

Revision ID: a84f65fedd57
Revises: 09d9d17d2500
Create Date: 2026-04-03 18:17:34.002069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84f65fedd57'
down_revision = '09d9d17d2500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_opening_submitted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qualification_opening_responded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pain_opening_submitted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pain_opening_responded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('link_fu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('link_fur', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('link_fur')
        batch_op.drop_column('link_fu')
        batch_op.drop_column('pain_opening_responded')
        batch_op.drop_column('pain_opening_submitted')
        batch_op.drop_column('qualification_opening_responded')
        batch_op.drop_column('qualification_opening_submitted')

    # ### end Alembic commands ###
