"""add workshop events

Revision ID: a8be502f5e26
Revises: bfe5eca377f9
Create Date: 2026-07-14 19:08:01.912524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8be502f5e26'
down_revision = 'bfe5eca377f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('inversion', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('clics', sa.Integer(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('whatsapp_leads', sa.Integer(), nullable=True),
    sa.Column('show_up', sa.Integer(), nullable=True),
    sa.Column('pitch_leads', sa.Integer(), nullable=True),
    sa.Column('pitch_final_leads', sa.Integer(), nullable=True),
    sa.Column('aplicaciones_form', sa.Integer(), nullable=True),
    sa.Column('agendas_exitosas', sa.Integer(), nullable=True),
    sa.Column('show_up_sales_call', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('cash_collected', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_events')),
    sa.UniqueConstraint('date', name=op.f('uq_workshop_events_date'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_events')
    # ### end Alembic commands ###
