"""Add setter daily stats and roles to questions

Revision ID: a9513d2f4439
Revises: 9f3b6f13d01a
Create Date: 2026-01-29 21:27:58.218643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9513d2f4439'
down_revision = '9f3b6f13d01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setter_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('inbound_leads', sa.Integer(), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=True),
    sa.Column('not_lead', sa.Integer(), nullable=True),
    sa.Column('new_offers', sa.Integer(), nullable=True),
    sa.Column('links_sent', sa.Integer(), nullable=True),
    sa.Column('appointments_booked', sa.Integer(), nullable=True),
    sa.Column('follow_ups', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setter_id'], ['users.id'], name=op.f('fk_setter_daily_stats_setter_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setter_daily_stats')),
    sa.UniqueConstraint('setter_id', 'date', name='_setter_date_uc')
    )
    with op.batch_alter_table('daily_report_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setter_stats_id', sa.Integer(), nullable=True))
        batch_op.alter_column('daily_stats_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_daily_report_answers_setter_stats_id_setter_daily_stats'), 'setter_daily_stats', ['setter_stats_id'], ['id'])

    with op.batch_alter_table('daily_report_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_report_questions', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('daily_report_answers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_report_answers_setter_stats_id_setter_daily_stats'), type_='foreignkey')
        batch_op.alter_column('daily_stats_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('setter_stats_id')

    op.drop_table('setter_daily_stats')
    # ### end Alembic commands ###
