"""Add hardcoded setter report fields

Revision ID: aec1be9d20b3
Revises: dafa6a28f2e5
Create Date: 2026-03-08 18:44:11.209389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec1be9d20b3'
down_revision = 'dafa6a28f2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_registrations'))
    )
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_entrantes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inbox_inabribles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inbox_leads', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opening_submitted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opening_responded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funnel_qualification', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funnel_pain', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funnel_offert', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funnel_link', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funnel_agenda', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_submitted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_responded', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('follow_up_responded')
        batch_op.drop_column('follow_up_submitted')
        batch_op.drop_column('funnel_agenda')
        batch_op.drop_column('funnel_link')
        batch_op.drop_column('funnel_offert')
        batch_op.drop_column('funnel_pain')
        batch_op.drop_column('funnel_qualification')
        batch_op.drop_column('opening_responded')
        batch_op.drop_column('opening_submitted')
        batch_op.drop_column('inbox_leads')
        batch_op.drop_column('inbox_inabribles')
        batch_op.drop_column('inbox_entrantes')

    op.drop_table('public_registrations')
    # ### end Alembic commands ###
