"""Add setter_id to appointments

Revision ID: b259a021a6b0
Revises: c7f30461356e
Create Date: 2026-02-10 11:21:47.769223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b259a021a6b0'
down_revision = 'c7f30461356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_setter_id_users'), 'users', ['setter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_setter_id_users'), type_='foreignkey')
        batch_op.drop_column('setter_id')

    # ### end Alembic commands ###
