"""add_excluded_sales

Revision ID: b2cbbef18715
Revises: 52504b1906e7
Create Date: 2026-06-03 15:44:11.793904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cbbef18715'
down_revision = '52504b1906e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excluded_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_temporal', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_excluded_sales')),
    sa.UniqueConstraint('marca_temporal', name=op.f('uq_excluded_sales_marca_temporal'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excluded_sales')
    # ### end Alembic commands ###
