"""add_appointment_metrics

Revision ID: b72f592453a7
Revises: 945674423935
Create Date: 2026-01-21 12:43:43.820855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72f592453a7'
down_revision = '945674423935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presentation_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_reschedule', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_from_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appointments_rescheduled_from', 'appointments', ['rescheduled_from_id'], ['id'])

    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots_defined', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('slots_defined')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_rescheduled_from', type_='foreignkey')
        batch_op.drop_column('rescheduled_from_id')
        batch_op.drop_column('is_reschedule')
        batch_op.drop_column('presentation_done')

    # ### end Alembic commands ###
