"""Add created_at to Appointment

Revision ID: bb425abc5c7b
Revises: 1b7d4485bc60
Create Date: 2026-02-06 16:08:39.113194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb425abc5c7b'
down_revision = '1b7d4485bc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
