"""add payload config to integration

Revision ID: bd14d8ed4b84
Revises: fe0242c48dc0
Create Date: 2026-01-26 13:40:10.025694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd14d8ed4b84'
down_revision = 'fe0242c48dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_column('payload_config')

    # ### end Alembic commands ###
