"""change_ad_spend_to_periods

Revision ID: bf3d8b7a84d9
Revises: 0bb40704bba5
Create Date: 2026-03-23 16:58:22.333839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3d8b7a84d9'
down_revision = '0bb40704bba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_period_spends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('entrantes', sa.Integer(), nullable=True),
    sa.Column('agendas', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('fk_ad_period_spends_ad_id_ads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_period_spends')),
    sa.UniqueConstraint('ad_id', 'start_date', 'end_date', name='uq_ad_period_spend')
    )
    op.drop_table('ad_daily_spends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_daily_spends',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ad_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('spend', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('entrantes', sa.INTEGER(), nullable=True),
    sa.Column('agendas', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('fk_ad_daily_spends_ad_id_ads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_daily_spends')),
    sa.UniqueConstraint('ad_id', 'date', name=op.f('uq_ad_daily_spend'))
    )
    op.drop_table('ad_period_spends')
    # ### end Alembic commands ###
