"""change triage daily report fields

Revision ID: bfe5eca377f9
Revises: d6d1714a8f87
Create Date: 2026-07-10 10:57:56.374340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe5eca377f9'
down_revision = 'd6d1714a8f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('today_agendas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('today_contacted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('today_confirmed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('today_canceled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('today_rescheduled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('future_agendas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('future_contacted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('future_confirmed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('future_canceled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('future_rescheduled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recoveries_contacted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recoveries_replied', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recoveries_scheduled', sa.Integer(), nullable=True))
        batch_op.drop_column('no_contestan')
        batch_op.drop_column('agendas_confirmadas')
        batch_op.drop_column('reprogramandos')
        batch_op.drop_column('seguimientos_contestados')
        batch_op.drop_column('cancelaciones')
        batch_op.drop_column('agendas_nuevas')
        batch_op.drop_column('seguimientos_iniciados')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seguimientos_iniciados', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('agendas_nuevas', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cancelaciones', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('seguimientos_contestados', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reprogramandos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('agendas_confirmadas', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('no_contestan', sa.INTEGER(), nullable=True))
        batch_op.drop_column('recoveries_scheduled')
        batch_op.drop_column('recoveries_replied')
        batch_op.drop_column('recoveries_contacted')
        batch_op.drop_column('future_rescheduled')
        batch_op.drop_column('future_canceled')
        batch_op.drop_column('future_confirmed')
        batch_op.drop_column('future_contacted')
        batch_op.drop_column('future_agendas')
        batch_op.drop_column('today_rescheduled')
        batch_op.drop_column('today_canceled')
        batch_op.drop_column('today_confirmed')
        batch_op.drop_column('today_contacted')
        batch_op.drop_column('today_agendas')

    # ### end Alembic commands ###
