"""add client_id a financial_sales, offer_presented a appointments, columnas renewal/upsell a closer_daily_reports, tabla client_merge_logs

Revision ID: c174c6b25233
Revises: a91421981706
Create Date: 2026-08-05 01:13:27.949041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c174c6b25233'
down_revision = 'a91421981706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_merge_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survivor_client_id', sa.Integer(), nullable=False),
    sa.Column('merged_client_id', sa.Integer(), nullable=False),
    sa.Column('matched_on', sa.String(length=50), nullable=True),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survivor_client_id'], ['clients.id'], name=op.f('fk_client_merge_logs_survivor_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_merge_logs'))
    )
    with op.batch_alter_table('client_merge_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_merge_logs_survivor_client_id'), ['survivor_client_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_presented', sa.Boolean(), nullable=True))

    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('renewal_cash_collected', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('renewal_in_call_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('renewal_in_call_cash', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('upsell_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upsell_cash_collected', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('upsell_in_call_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upsell_in_call_cash', sa.Float(), nullable=True))

    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_financial_sales_client_id'), ['client_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_financial_sales_client_id_clients'), 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_financial_sales_client_id_clients'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_financial_sales_client_id'))
        batch_op.drop_column('client_id')

    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('upsell_in_call_cash')
        batch_op.drop_column('upsell_in_call_count')
        batch_op.drop_column('upsell_cash_collected')
        batch_op.drop_column('upsell_count')
        batch_op.drop_column('renewal_in_call_cash')
        batch_op.drop_column('renewal_in_call_count')
        batch_op.drop_column('renewal_cash_collected')
        batch_op.drop_column('renewal_count')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('offer_presented')

    with op.batch_alter_table('client_merge_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_merge_logs_survivor_client_id'))

    op.drop_table('client_merge_logs')
    # ### end Alembic commands ###
