"""Added setter daily stage metrics

Revision ID: c17ee28580ce
Revises: 12d53c811fe5
Create Date: 2026-02-11 19:44:04.035955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17ee28580ce'
down_revision = '12d53c811fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setter_daily_stage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_stats_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_stats_id'], ['setter_daily_stats.id'], name=op.f('fk_setter_daily_stage_metrics_daily_stats_id_setter_daily_stats')),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], name=op.f('fk_setter_daily_stage_metrics_stage_id_pipeline_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setter_daily_stage_metrics')),
    sa.UniqueConstraint('daily_stats_id', 'stage_id', name='_setter_daily_stage_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setter_daily_stage_metrics')
    # ### end Alembic commands ###
