"""add_is_non_working_day_to_report_models

Revision ID: c9ec326adaa9
Revises: 686f8945d822
Create Date: 2026-07-20 21:00:21.768033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ec326adaa9'
down_revision = '686f8945d822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_non_working_day', sa.Boolean(), server_default='0', nullable=True))

    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_non_working_day', sa.Boolean(), server_default='0', nullable=True))

    with op.batch_alter_table('triage_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_non_working_day', sa.Boolean(), server_default='0', nullable=True))

    with op.batch_alter_table('triage_tracker_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_non_working_day', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_tracker_reports', schema=None) as batch_op:
        batch_op.drop_column('is_non_working_day')

    with op.batch_alter_table('triage_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('is_non_working_day')

    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('is_non_working_day')

    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('is_non_working_day')

    # ### end Alembic commands ###
