"""add followup_reminder_sent_at to appointments

Revision ID: ca66e36b5bca
Revises: 75aea94ff0e5
Create Date: 2026-08-06 20:08:42.570686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca66e36b5bca'
down_revision = '75aea94ff0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followup_reminder_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('followup_reminder_sent_at')

    # ### end Alembic commands ###
