"""Add last_stage to manychat_leads

Revision ID: cd24f91644eb
Revises: e4cb4dfe0ad3
Create Date: 2026-04-09 19:30:30.141181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd24f91644eb'
down_revision = 'e4cb4dfe0ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manychat_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_stage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manychat_leads', schema=None) as batch_op:
        batch_op.drop_column('last_stage')

    # ### end Alembic commands ###
