"""Add error resolution fields to FinancialSale

Revision ID: cff139f1ae7e
Revises: 8be8fdeb9fdd
Create Date: 2026-03-18 18:14:56.817523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff139f1ae7e'
down_revision = '8be8fdeb9fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('error_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('product', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.drop_column('payment_type')
        batch_op.drop_column('product')
        batch_op.drop_column('error_notes')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
