"""Add AdDailySpend model

Revision ID: d1c1015ccf9c
Revises: 5dea270e5e8a
Create Date: 2026-03-11 01:20:56.637363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c1015ccf9c'
down_revision = '5dea270e5e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_daily_spends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('fk_ad_daily_spends_ad_id_ads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_daily_spends')),
    sa.UniqueConstraint('ad_id', 'date', name='uq_ad_daily_spend')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_daily_spends')
    # ### end Alembic commands ###
