"""Add PaymentMethod and update Payment

Revision ID: d4ab66005f0e
Revises: d10d03582c72
Create Date: 2026-01-13 01:42:46.855343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ab66005f0e'
down_revision = 'd10d03582c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('commission_percent', sa.Float(), nullable=True),
    sa.Column('commission_fixed', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_payments_payment_method_id_payment_methods', 'payment_methods', ['payment_method_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('payment_type')
        batch_op.drop_column('payment_method_id')

    op.drop_table('payment_methods')
    # ### end Alembic commands ###
