"""change followups recoveries and referrals in closer report

Revision ID: d6d1714a8f87
Revises: 3815fdf62b80
Create Date: 2026-07-10 10:07:04.368679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d1714a8f87'
down_revision = '3815fdf62b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_ups_closed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recoveries_contacted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recoveries_replied', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recoveries_scheduled', sa.Integer(), nullable=True))
        batch_op.drop_column('referrals_contacted')
        batch_op.drop_column('follow_ups_cold_replied')
        batch_op.drop_column('follow_ups_cold_scheduled')
        batch_op.drop_column('follow_ups_hot_replied')
        batch_op.drop_column('follow_ups_hot_sent')
        batch_op.drop_column('follow_ups_cold_sent')
        batch_op.drop_column('follow_ups_hot_scheduled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_ups_hot_scheduled', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_cold_sent', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_hot_sent', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_hot_replied', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_cold_scheduled', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('follow_ups_cold_replied', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('referrals_contacted', sa.INTEGER(), nullable=True))
        batch_op.drop_column('recoveries_scheduled')
        batch_op.drop_column('recoveries_replied')
        batch_op.drop_column('recoveries_contacted')
        batch_op.drop_column('follow_ups_closed')

    # ### end Alembic commands ###
