"""add utm logs

Revision ID: d76d56c44ad5
Revises: 0f1edb36526b
Create Date: 2026-05-04 23:03:55.644379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76d56c44ad5'
down_revision = '0f1edb36526b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('final_url', sa.String(length=1000), nullable=False),
    sa.Column('utm_source', sa.String(length=50), nullable=True),
    sa.Column('utm_medium', sa.String(length=50), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_utm_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utm_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utm_logs')
    # ### end Alembic commands ###
