"""Added instagram to financial_sales and created financial_agendas table

Revision ID: d942a9da2664
Revises: a84f65fedd57
Create Date: 2026-04-08 21:13:43.421834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd942a9da2664'
down_revision = 'a84f65fedd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setter_name', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=True),
    sa.Column('closer_name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_notes', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_agendas'))
    )
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_sales', schema=None) as batch_op:
        batch_op.drop_column('instagram')

    op.drop_table('financial_agendas')
    # ### end Alembic commands ###
