"""add parent_id to Comment for thread replies

Revision ID: da0c8ee3507e
Revises: 477538b05ccf
Create Date: 2026-05-25 17:54:37.742740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0c8ee3507e'
down_revision = '477538b05ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_parent_id_comments'), 'comments', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_parent_id_comments'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
