"""rename funnel_offert to funnel_offer

Revision ID: e398e0e02d0c
Revises: aec1be9d20b3
Create Date: 2026-03-08 19:17:20.567479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e398e0e02d0c'
down_revision = 'aec1be9d20b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funnel_offer', sa.Integer(), nullable=True))
        batch_op.drop_column('funnel_offert')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setter_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funnel_offert', sa.INTEGER(), nullable=True))
        batch_op.drop_column('funnel_offer')

    # ### end Alembic commands ###
