"""Add funnel_step and last_stage to leads

Revision ID: e4cb4dfe0ad3
Revises: 2801cbf60c67
Create Date: 2026-04-09 19:16:29.971086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cb4dfe0ad3'
down_revision = '2801cbf60c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funnel_step', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_stage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('last_stage')
        batch_op.drop_column('funnel_step')

    # ### end Alembic commands ###
