"""Add ManychatAdLead model and entrantes agendas to AdDailySpend

Revision ID: e50741211157
Revises: d1c1015ccf9c
Create Date: 2026-03-11 01:35:23.896019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50741211157'
down_revision = 'd1c1015ccf9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manychat_ad_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manychat_id', sa.String(length=100), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('fk_manychat_ad_leads_ad_id_ads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manychat_ad_leads')),
    sa.UniqueConstraint('manychat_id', name=op.f('uq_manychat_ad_leads_manychat_id'))
    )
    with op.batch_alter_table('ad_daily_spends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrantes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agendas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_daily_spends', schema=None) as batch_op:
        batch_op.drop_column('agendas')
        batch_op.drop_column('entrantes')

    op.drop_table('manychat_ad_leads')
    # ### end Alembic commands ###
