"""Refactor TriageDailyReport to use name instead of user ID

Revision ID: edfbc2b017ba
Revises: 693d6daeeec8
Create Date: 2026-03-15 16:05:36.623397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfbc2b017ba'
down_revision = '693d6daeeec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triage_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('_triage_report_date_uc'), type_='unique')
        batch_op.create_unique_constraint('_triage_report_date_uc', ['triage_name', 'date'])
        batch_op.drop_constraint(batch_op.f('fk_triage_daily_reports_triage_id_users'), type_='foreignkey')
        batch_op.drop_column('triage_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triage_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_triage_daily_reports_triage_id_users'), 'users', ['triage_id'], ['id'])
        batch_op.drop_constraint('_triage_report_date_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_triage_report_date_uc'), ['triage_id', 'date'])
        batch_op.drop_column('triage_name')

    # ### end Alembic commands ###
