"""add installment fields to CloserDailyReport

Revision ID: f5547202180b
Revises: 78a6be16b10f
Create Date: 2026-05-27 20:38:48.382740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5547202180b'
down_revision = '78a6be16b10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_cash_collected', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('installment_in_call_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_in_call_cash', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_reports', schema=None) as batch_op:
        batch_op.drop_column('installment_in_call_cash')
        batch_op.drop_column('installment_in_call_count')
        batch_op.drop_column('installment_cash_collected')
        batch_op.drop_column('installment_count')

    # ### end Alembic commands ###
