"""add ManychatLead and LeadAnswer models

Revision ID: f81b03cc494e
Revises: 48365a06c112
Create Date: 2026-03-13 11:30:44.052321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81b03cc494e'
down_revision = '48365a06c112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manychat_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manychat_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('ig', sa.String(length=100), nullable=True),
    sa.Column('follower', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manychat_leads')),
    sa.UniqueConstraint('manychat_id', name=op.f('uq_manychat_leads_manychat_id'))
    )
    op.create_table('lead_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.Column('fecha_recibida', sa.String(length=50), nullable=True),
    sa.Column('opening', sa.String(length=100), nullable=True),
    sa.Column('variante', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['manychat_leads.id'], name=op.f('fk_lead_answers_lead_id_manychat_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_answers'))
    )
    with op.batch_alter_table('manychat_ad_leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_manychat_ad_leads_manychat_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_manychat_ad_leads_ad_id_ads'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manychat_ad_leads', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_manychat_ad_leads_ad_id_ads'), 'ads', ['ad_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_manychat_ad_leads_manychat_id'), ['manychat_id'])

    op.drop_table('lead_answers')
    op.drop_table('manychat_leads')
    # ### end Alembic commands ###
