"""Optimizacion de indices y rendimiento

Revision ID: f83ef7f1cc72
Revises: 49256092400d
Create Date: 2026-06-26 23:36:34.426671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83ef7f1cc72'
down_revision = '49256092400d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_closer_id'), ['closer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_program_id'), ['program_id'], unique=False)

    with op.batch_alter_table('lead_event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_event_logs_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_event_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_method_id'), ['payment_method_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_payment_method_id'))
        batch_op.drop_index(batch_op.f('ix_payments_enrollment_id'))

    with op.batch_alter_table('lead_event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_event_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_lead_event_logs_appointment_id'))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_program_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_closer_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_client_id'))

    # ### end Alembic commands ###
