"""restore redirect_url_success

Revision ID: f8484373db24
Revises: 237fb3603183
Create Date: 2026-02-11 14:19:57.151496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8484373db24'
down_revision = '237fb3603183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirect_url_success', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('redirect_url_success')

    # ### end Alembic commands ###
