"""add_follow_up_fields_to_appointment

Revision ID: fbec71fd9b9f
Revises: c9ec326adaa9
Create Date: 2026-07-20 21:59:08.132426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec71fd9b9f'
down_revision = 'c9ec326adaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_seguimiento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seguimiento_realizado', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('seguimiento_realizado')
        batch_op.drop_column('fecha_seguimiento')

    # ### end Alembic commands ###
