"""add closer alias model

Revision ID: fcdeb1157b85
Revises: 80c788051ebb
Create Date: 2026-06-23 21:29:06.910671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdeb1157b85'
down_revision = '80c788051ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closer_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_closer_aliases_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_closer_aliases'))
    )
    with op.batch_alter_table('closer_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closer_aliases_alias_name'), ['alias_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closer_aliases_alias_name'))

    op.drop_table('closer_aliases')
    # ### end Alembic commands ###
