"""Add id_option_send to LeadAnswer

Revision ID: fdc53a87bd00
Revises: a1cb54d00976
Create Date: 2026-05-14 12:46:35.605905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc53a87bd00'
down_revision = 'a1cb54d00976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_option_send', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_answers', schema=None) as batch_op:
        batch_op.drop_column('id_option_send')

    # ### end Alembic commands ###
