"""add_question_scopes

Revision ID: fe0242c48dc0
Revises: 6a4038ba886e
Create Date: 2026-01-25 21:07:54.527625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0242c48dc0'
down_revision = '6a4038ba886e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_survey_questions_group_id_event_groups'), 'event_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_survey_questions_group_id_event_groups'), type_='foreignkey')
        batch_op.drop_column('is_global')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
